version: "3.7"

services:
  application:
    container_name: ${_Values_root_name}-application
    image: ${_Values_image_repository}-native${_Values_server_arch}:${_Values_image_tag}
#    image: ${_Values_image_repository}:${_Values_image_tag}
    restart: 'no'
    ports:
      - "${_Values_service_port}:${_Values_service_port}"
    command: [ "-Xmx${_Values_resources_requests_memory}" ]
    environment:
      #auth
      spring.security.authorization.base-uri: "/"
      spring.security.authorization.clients: "oauth2-proxy:none"
      spring.security.authorization.users: "user1:user1,user2:user2,user3:user3,user4:user4"
    networks:
      - ${_Values_root_name}-net

  nginx:
    container_name: ${_Values_root_name}-nginx
    image: nginx:1.22.1
    restart: 'no'
    ports:
      - 8080:80
    #      - 444:443
    networks:
      - ${_Values_root_name}-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl/
    depends_on:
      application:
        condition: service_started

volumes:
    tmp:
    applogs:
    pgdata:

networks:
  auth-server-net:
    driver: bridge