#application
server:
  port: 30200
  tomcat.threads.max: 20
  forward-headers-strategy: FRAMEWORK


#monitoring
management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "health,prometheus,heapdump"

logging:
  level:
    root: info
    org.springframework.security: trace

spring.security.authorization.base-uri: "/"
spring.security.authorization.clients: "oauth2-proxy:none"
spring.security.authorization.users: "user1:user1,user2:user2,user3:user3"
