#application
server:
  port: 8081
  tomcat.threads.max: 20

#monitoring
management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "health,prometheus,heapdump"

logging:
  level:
    root: info
    org.springframework.security: trace

spring.security.base-endpoint: /oauth2